export const softwareEngineerJobDescription = `Job Title: Software Engineer

Role Summary: We are looking for a Software Engineer to join our diverse and dedicated team. This position is an excellent opportunity for those seeking to grow their skills and experience in software development while working on projects with significant impact.

Responsibilities:
- Develop and implement new software solutions.
- Collaborate with teams to understand objectives, design features, and meet specific requirements.
- Improve and maintain existing software to ensure strong functionality and optimization.
- Recommend changes to existing software applications, as necessary, to ensure excellent functionality.
- Write efficient, secure, well-documented, and clean JavaScript code.
- Participate in all phases of the development life cycle.

Requirements:
- Degree in Computer Science or related field.
- 0-3 years of experience in software development.
- Demonstrated problem-solving abilities and attention to detail.
- Proficiency with at least one programming language.
- Familiarity with various operating systems and platforms.
- Good understanding of software development principles.
- Excellent communication and teamwork skills.
- Demonstrated ability to manage and prioritize tasks independently.`;

export const openAIPrompt = `Based on this job description, I need you to generate 10 interview questions relevant to the role, 
responsibilities, and qualifications mentioned, divided between technical and behavioural aspects. 
Each question should be suitable for assessing the candidate's fit for the position.

Furthermore, for each question, please write three incorrect answers and one correct answer.
Make sure that the attribute "incorrectAnswers" is a 2D array, with each array inside containing 
three incorrect answers relevant to the question asked. For example, in the "incorrectAnswers" 2D 
array, each index represents the question relevant. To further explain what I mean, incorrectAnswers[0] 
represents the array containing the three incorrect answers for behavioral question 1, 
incorrectAnswers[1] represents the array containing the three incorrect answers for behavioral
question 2, and so on.

Please generate the response in the following JSON format, strictly adhering to the structure provided, 
and ensure there are no backticks, no additional text, or formatting. Remember, everything that is between
angle brackets should be generated by you and relevant to the instructions I have provided:
      
{
  response: {
    behavioral: {
      questions: [
        "<generated behavioral question 1>",
        "<generated behavioral question 2>",
        "<generated behavioral question 3>",
        "<generated behavioral question 4>",
        "<generated behavioral question 5>",
      ],
      correctAnswers: [
        "<correct answer for behavioral question 1>",
        "<correct answer for behavioral question 2>",
        "<correct answer for behavioral question 3>",
        "<correct answer for behavioral question 4>",
        "<correct answer for behavioral question 5>",
      ],
      incorrectAnswers: [
        [
          "<incorrect answer 1 for behavioral question 1>",
          "<incorrect answer 2 for behavioral question 1>",
          "<incorrect answer 3 for behavioral question 1>",
        ],
        [
          "<incorrect answer 1 for behavioral question 2>",
          "<incorrect answer 2 for behavioral question 2>",
          "<incorrect answer 3 for behavioral question 2>",
        ],
        [
          "<incorrect answer 1 for behavioral question 3>",
          "<incorrect answer 2 for behavioral question 3>",
          "<incorrect answer 3 for behavioral question 3>",
        ],
        [
          "<incorrect answer 1 for behavioral question 4>",
          "<incorrect answer 2 for behavioral question 4>",
          "<incorrect answer 3 for behavioral question 4>",
        ],
        [
          "<incorrect answer 1 for behavioral question 5>",
          "<incorrect answer 2 for behavioral question 5>",
          "<incorrect answer 3 for behavioral question 5>",
        ],
      ],
    },
    technical: {
      questions: [
        "<generated technical question 1>",
        "<generated technical question 2>",
        "<generated technical question 3>",
        "<generated technical question 4>",
        "<generated technical question 5>",
      ],
      correctAnswers: [
        "<correct answer for technical question 1>",
        "<correct answer for technical question 2>",
        "<correct answer for technical question 3>",
        "<correct answer for technical question 4>",
        "<correct answer for technical question 5>",
      ],
      incorrectAnswers: [
        [
          "<incorrect answer 1 for technical question 1>",
          "<incorrect answer 2 for technical question 1>",
          "<incorrect answer 3 for technical question 1>",
        ],
        [
          "<incorrect answer 1 for technical question 2>",
          "<incorrect answer 2 for technical question 2>",
          "<incorrect answer 3 for technical question 2>",
        ],
        [
          "<incorrect answer 1 for technical question 3>",
          "<incorrect answer 2 for technical question 3>",
          "<incorrect answer 3 for technical question 3>",
        ],
        [
          "<incorrect answer 1 for technical question 4>",
          "<incorrect answer 2 for technical question 4>",
          "<incorrect answer 3 for technical question 4>",
        ],
        [
          "<incorrect answer 1 for technical question 5>",
          "<incorrect answer 2 for technical question 5>",
          "<incorrect answer 3 for technical question 5>",
        ],
      ],
    },
  },
}`;
